export { requireAdmin, type AdminSession } from '@/modules/admin/auth';
export {
  listAdminOrders,
  getAdminOrder,
  transitionAdminOrderStatus,
  cancelAdminOrder,
} from '@/modules/admin/orders';
export {
  listAdminCategories,
  createAdminCategory,
  updateAdminCategory,
  archiveAdminCategory,
  listAdminProducts,
  getAdminProduct,
  createAdminProduct,
  updateAdminProduct,
  setProductAvailability,
  archiveAdminProduct,
  uploadProductImage,
  deleteProductImage,
  listAdminAddons,
  createAdminAddon,
  updateAdminAddon,
  archiveAdminAddon,
  getAdminStore,
  updateAdminStore,
  setStoreAcceptingOrders,
  getStoreAcceptingOrders,
  listAdminBusinessHours,
  replaceAdminBusinessHours,
  listAdminBlackouts,
  createAdminBlackout,
  deleteAdminBlackout,
} from '@/modules/admin/catalog';
export { listAdminAuditLogs, writeAuditLog } from '@/modules/admin/audit';
export {
  nextAdminStatus,
  type AdminOrderListItem,
  type AdminOrderDetail,
  type AdminProduct,
  type AdminCategory,
  type AdminAddon,
  type AdminBlackout,
  type AdminAuditLog,
  type AdminProductImage,
  type AdminBusinessHourInput,
} from '@/modules/admin/types';
