/** Headers aplicados em todas as rotas via next.config. */
export const SECURITY_HEADERS: Array<{ key: string; value: string }> = [
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=(), payment=()',
  },
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload',
  },
  {
    key: 'Content-Security-Policy',
    value: [
      "default-src 'self'",
      "base-uri 'self'",
      "form-action 'self'",
      "frame-ancestors 'none'",
      "object-src 'none'",
      "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://challenges.cloudflare.com",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data: blob: https:",
      "font-src 'self' data:",
      [
        "connect-src 'self'",
        'http://127.0.0.1:54321',
        'ws://127.0.0.1:54321',
        'ws://127.0.0.1:3000',
        'http://localhost:54321',
        'ws://localhost:54321',
        'ws://localhost:3000',
        'https://*.supabase.co',
        'wss://*.supabase.co',
        'https://challenges.cloudflare.com',
        'https://nominatim.openstreetmap.org',
        'https://*.tile.openstreetmap.org',
        'https://tile.openstreetmap.org',
        'https://router.project-osrm.org',
        'https://*.ingest.sentry.io',
        'https://*.sentry.io',
        'https://maps.googleapis.com',
      ].join(' '),
      "frame-src https://challenges.cloudflare.com https://www.openstreetmap.org",
      'upgrade-insecure-requests',
    ].join('; '),
  },
];
